services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongo1,mongo2,mongo3/lazy_english?replicaSet=rs0
      - TZ=Asia/Bangkok
    env_file:
      - .env
    volumes:
      - ./serviceAccountKey.json:/usr/src/app/serviceAccountKey.json
      - ./.env:/usr/src/app/.env
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db
    depends_on:
      - mongo2
      - mongo3

  mongo2:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - mongo2-data:/data/db

  mongo3:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - mongo3-data:/data/db

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: >
      bash -c "
        sleep 10 &&
        mongosh --host mongo1:27017 --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [
              {_id: 0, host: \"mongo1:27017\"},
              {_id: 1, host: \"mongo2:27017\"},
              {_id: 2, host: \"mongo3:27017\"}
            ]
          })
        '
      "

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
